### ISSUE TITLE
Cannot use navigation buttons

### ISSUE THREAD

**Issue by kikijiki** [Raphlette/obsidian-new-tab-plus#2]
If this plugin is enabled, clicking on the back or forward arrows will open new tabs.
I think the expected behavior here is to stay on the same tab,

**Comment by Raphlette** [comment]
Indeed the expected behavior would be to stay on the same tab. 
But at the same time, you might open a file twice. (As after opening a file, I switch it back to the previous file and open the new file in a new tab. Therefore, on the old tab, the new 'previous file' is now the file we just opened.)

Could you give me some context as to when you had these arrows ? Normally, if you start fresh (no tab open) as we open a new file, it should only appears on the previously focused tab.

**Comment by kikijiki** [comment]
When I open a link with this plugin, the current tab ends up staying the same and the new file open in a new tab, but the current tab too temporarily switches to that new file and immediately back, and that affects the tab history. For example this is how tab "a" becomes after opening "b" and "c":

![image](https://github.com/Raphlette/obsidian-new-tab-plus/assets/784077/b32e4c58-6083-4a92-9cd9-820604b723ef)

It's not a big deal so feel free to close.

**Comment by Raphlette** [comment]
Right, as you technically open the page b or c in a new tab, I didn't think someone would want to use the history. 
I guess I could check if it's possible to clear the history or/and  just prevent the plugin to process. 

I'll make some tests. 
Thanks for the feedback !
